export interface Product {
  id: string;
  name: string;
  category: 'carbonated' | 'alcohol' | 'snacks' | 'nuts';
  servingSize: string;
  servingMl?: number;
  servingG?: number;
  calories: number;
  sugar: number;
  protein: number;
  fat: number;
  carbs: number;
  ingredients: string[];
  isHealthy: boolean;
  healthNote?: string;
  image: string;
}

export const CATEGORIES = {
  all: 'ყველა',
  carbonated: 'გაზიანი სასმელები',
  alcohol: 'ალკოჰოლური სასმელები',
  snacks: 'სნექები',
  nuts: 'თხილეული',
  healthy: 'შაქრის გარეშე',
} as const;

export type CategoryKey = keyof typeof CATEGORIES;

export const products: Product[] = [
  // === გაზიანი სასმელები ===
  {
    id: 'redbull',
    name: 'Red Bull',
    category: 'carbonated',
    servingSize: '250 მლ',
    servingMl: 250,
    calories: 110,
    sugar: 27,
    protein: 0,
    fat: 0,
    carbs: 28,
    ingredients: ['წყალი', 'შაქარი', 'გლუკოზა', 'ტაურინი', 'გლუკურონოლაქტონი', 'კოფეინი', 'B ჯგუფის ვიტამინები', 'არომატიზატორები'],
    isHealthy: false,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Red_Bull_energy_drinks.jpg/250px-Red_Bull_energy_drinks.jpg',
  },
  {
    id: 'redbull-sugarfree',
    name: 'Red Bull Sugar Free',
    category: 'carbonated',
    servingSize: '250 მლ',
    servingMl: 250,
    calories: 5,
    sugar: 0,
    protein: 0,
    fat: 0,
    carbs: 0,
    ingredients: ['წყალი', 'ლიმონმჟავა', 'ტაურინი', 'ნატრიუმის ბიკარბონატი', 'მაგნიუმის კარბონატი', 'კოფეინი', 'გლუკურონოლაქტონი', 'დამატკბობლები (ასპარტამი, აცესულფამი K)', 'B ჯგუფის ვიტამინები', 'არომატიზატორები'],
    isHealthy: true,
    healthNote: 'არ შეიცავს შაქარს. ხელოვნური დამატკბობლები გამოიყენება. კოფეინის შემცველობა 80 მგ. ზომიერად მიღება მისაღებია.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Red_Bull_energy_drinks.jpg/250px-Red_Bull_energy_drinks.jpg',
  },
  {
    id: 'coca-cola',
    name: 'Coca-Cola',
    category: 'carbonated',
    servingSize: '330 მლ',
    servingMl: 330,
    calories: 139,
    sugar: 35,
    protein: 0,
    fat: 0,
    carbs: 35,
    ingredients: ['წყალი', 'შაქარი', 'კარამელის საღებავი', 'ფოსფორმჟავა', 'ნატურალური არომატიზატორები', 'კოფეინი'],
    isHealthy: false,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Coca-Cola_bottle_%286699404437%29.jpg/250px-Coca-Cola_bottle_%286699404437%29.jpg',
  },
  {
    id: 'fanta',
    name: 'Fanta',
    category: 'carbonated',
    servingSize: '330 მლ',
    servingMl: 330,
    calories: 156,
    sugar: 38,
    protein: 0,
    fat: 0,
    carbs: 39,
    ingredients: ['წყალი', 'შაქარი', 'ფორთოხლის წვენი 3%', 'ლიმონმჟავა', 'ნატურალური არომატიზატორები', 'ბეტა-კაროტინი'],
    isHealthy: false,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Fanta_300ml_Bottle.jpg/250px-Fanta_300ml_Bottle.jpg',
  },
  {
    id: 'sprite',
    name: 'Sprite',
    category: 'carbonated',
    servingSize: '330 მლ',
    servingMl: 330,
    calories: 128,
    sugar: 32,
    protein: 0,
    fat: 0,
    carbs: 32,
    ingredients: ['წყალი', 'შაქარი', 'ლიმონმჟავა', 'ნატურალური არომატიზატორები'],
    isHealthy: false,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Sprite_cans.jpg/250px-Sprite_cans.jpg',
  },
  {
    id: 'pepsi',
    name: 'Pepsi',
    category: 'carbonated',
    servingSize: '330 მლ',
    servingMl: 330,
    calories: 140,
    sugar: 36,
    protein: 0,
    fat: 0,
    carbs: 36,
    ingredients: ['წყალი', 'შაქარი', 'კარამელის საღებავი', 'ფოსფორმჟავა', 'კოფეინი', 'ნატურალური არომატიზატორები'],
    isHealthy: false,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Pepsi_Can.jpg/250px-Pepsi_Can.jpg',
  },
  {
    id: 'limonati-tarhun',
    name: 'ლიმონათი ტარხუნა',
    category: 'carbonated',
    servingSize: '500 მლ',
    servingMl: 500,
    calories: 210,
    sugar: 52,
    protein: 0,
    fat: 0,
    carbs: 53,
    ingredients: ['წყალი', 'შაქარი', 'ტარხუნის ექსტრაქტი', 'ლიმონმჟავა', 'საღებავი', 'არომატიზატორი'],
    isHealthy: false,
    image: '/products/limonati-tarhun.svg',
  },
  {
    id: 'limonati-feijoa',
    name: 'ლიმონათი ფეიხოა',
    category: 'carbonated',
    servingSize: '500 მლ',
    servingMl: 500,
    calories: 200,
    sugar: 50,
    protein: 0,
    fat: 0,
    carbs: 50,
    ingredients: ['წყალი', 'შაქარი', 'ფეიხოას ექსტრაქტი', 'ლიმონმჟავა', 'არომატიზატორი'],
    isHealthy: false,
    image: '/products/limonati-feijoa.svg',
  },
  {
    id: 'coca-cola-zero',
    name: 'Coca-Cola Zero',
    category: 'carbonated',
    servingSize: '330 მლ',
    servingMl: 330,
    calories: 1,
    sugar: 0,
    protein: 0,
    fat: 0,
    carbs: 0,
    ingredients: ['წყალი', 'კარამელის საღებავი', 'ფოსფორმჟავა', 'დამატკბობლები (ასპარტამი, აცესულფამი K)', 'კოფეინი'],
    isHealthy: true,
    healthNote: 'არ შეიცავს შაქარს. ხელოვნური დამატკბობლები გამოიყენება. ზომიერად მიღება მისაღებია.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Coca_Cola_Zero_02.jpg/250px-Coca_Cola_Zero_02.jpg',
  },
  {
    id: 'borjomi',
    name: 'ბორჯომი',
    category: 'carbonated',
    servingSize: '500 მლ',
    servingMl: 500,
    calories: 0,
    sugar: 0,
    protein: 0,
    fat: 0,
    carbs: 0,
    ingredients: ['ნატურალური მინერალური წყალი', 'ნახშირორჟანგი'],
    isHealthy: true,
    healthNote: 'ნატურალური მინერალური წყალი. მინერალებით მდიდარი. ყოველდღიური მიღება რეკომენდირებულია.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Borjomi_mineral_water.jpg/250px-Borjomi_mineral_water.jpg',
  },
  {
    id: 'nabeghlavi',
    name: 'ნაბეღლავი',
    category: 'carbonated',
    servingSize: '500 მლ',
    servingMl: 500,
    calories: 0,
    sugar: 0,
    protein: 0,
    fat: 0,
    carbs: 0,
    ingredients: ['ნატურალური მინერალური წყალი', 'ნახშირორჟანგი'],
    isHealthy: true,
    healthNote: 'ნატურალური მინერალური წყალი. ბიკარბონატებითა და მინერალებით მდიდარი.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Nabeghlavi.jpg/250px-Nabeghlavi.jpg',
  },
  {
    id: 'monster',
    name: 'Monster Energy',
    category: 'carbonated',
    servingSize: '500 მლ',
    servingMl: 500,
    calories: 220,
    sugar: 54,
    protein: 0,
    fat: 0,
    carbs: 56,
    ingredients: ['წყალი', 'შაქარი', 'გლუკოზა', 'ლიმონმჟავა', 'ტაურინი', 'კოფეინი', 'B ვიტამინები', 'გუარანა', 'ჟინსენგი'],
    isHealthy: false,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Monster_Energy_drink_%28cropped%29.jpg/250px-Monster_Energy_drink_%28cropped%29.jpg',
  },

  // === ალკოჰოლური სასმელები ===
  {
    id: 'beer-argo',
    name: 'არგო ლუდი',
    category: 'alcohol',
    servingSize: '500 მლ',
    servingMl: 500,
    calories: 215,
    sugar: 0,
    protein: 2,
    fat: 0,
    carbs: 17,
    ingredients: ['წყალი', 'ალაო', 'სვია', 'საფუარი'],
    isHealthy: false,
    image: '/products/beer.svg',
  },
  {
    id: 'beer-natakhtari',
    name: 'ნატახტარი ლუდი',
    category: 'alcohol',
    servingSize: '500 მლ',
    servingMl: 500,
    calories: 210,
    sugar: 0,
    protein: 1.5,
    fat: 0,
    carbs: 16,
    ingredients: ['წყალი', 'ალაო', 'სვია', 'საფუარი'],
    isHealthy: false,
    image: '/products/beer.svg',
  },
  {
    id: 'wine-red',
    name: 'წითელი ღვინო (საფერავი)',
    category: 'alcohol',
    servingSize: '150 მლ',
    servingMl: 150,
    calories: 125,
    sugar: 0.9,
    protein: 0.1,
    fat: 0,
    carbs: 3.8,
    ingredients: ['ყურძნის წვენი', 'საფუარი', 'სულფიტები'],
    isHealthy: false,
    healthNote: 'ზომიერად მიღებისას შეიცავს ანტიოქსიდანტებს, მაგრამ ალკოჰოლის მავნე ეფექტი აჭარბებს.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Red_Wine_Glas.jpg/250px-Red_Wine_Glas.jpg',
  },
  {
    id: 'wine-white',
    name: 'თეთრი ღვინო (რქაწითელი)',
    category: 'alcohol',
    servingSize: '150 მლ',
    servingMl: 150,
    calories: 121,
    sugar: 1.4,
    protein: 0.1,
    fat: 0,
    carbs: 3.8,
    ingredients: ['ყურძნის წვენი', 'საფუარი', 'სულფიტები'],
    isHealthy: false,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/White_wine_glass.jpg/250px-White_wine_glass.jpg',
  },
  {
    id: 'chacha',
    name: 'ჭაჭა',
    category: 'alcohol',
    servingSize: '50 მლ',
    servingMl: 50,
    calories: 120,
    sugar: 0,
    protein: 0,
    fat: 0,
    carbs: 0,
    ingredients: ['ყურძნის ნაჭაჭი', 'სპირტი'],
    isHealthy: false,
    image: '/products/spirits.svg',
  },
  {
    id: 'vodka',
    name: 'არაყი',
    category: 'alcohol',
    servingSize: '50 მლ',
    servingMl: 50,
    calories: 110,
    sugar: 0,
    protein: 0,
    fat: 0,
    carbs: 0,
    ingredients: ['სპირტი', 'წყალი'],
    isHealthy: false,
    image: '/products/spirits.svg',
  },
  {
    id: 'whiskey',
    name: 'ვისკი',
    category: 'alcohol',
    servingSize: '50 მლ',
    servingMl: 50,
    calories: 110,
    sugar: 0,
    protein: 0,
    fat: 0,
    carbs: 0,
    ingredients: ['ალაოს სპირტი', 'წყალი'],
    isHealthy: false,
    image: '/products/spirits.svg',
  },
  {
    id: 'beer-heineken',
    name: 'Heineken',
    category: 'alcohol',
    servingSize: '330 მლ',
    servingMl: 330,
    calories: 138,
    sugar: 0,
    protein: 1,
    fat: 0,
    carbs: 11,
    ingredients: ['წყალი', 'ალაო', 'სვია', 'საფუარი'],
    isHealthy: false,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Heineken_Bottle.jpg/250px-Heineken_Bottle.jpg',
  },

  // === სნექები ===
  {
    id: 'lays-classic',
    name: 'Lay\'s კლასიკური',
    category: 'snacks',
    servingSize: '100 გ',
    servingG: 100,
    calories: 536,
    sugar: 0.5,
    protein: 6.5,
    fat: 33,
    carbs: 53,
    ingredients: ['კარტოფილი', 'მცენარეული ზეთი', 'მარილი'],
    isHealthy: false,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/A_Lay%27s_Stax_chip.jpg/250px-A_Lay%27s_Stax_chip.jpg',
  },
  {
    id: 'doritos',
    name: 'Doritos',
    category: 'snacks',
    servingSize: '100 გ',
    servingG: 100,
    calories: 496,
    sugar: 3.5,
    protein: 7,
    fat: 25,
    carbs: 60,
    ingredients: ['სიმინდის ფქვილი', 'მცენარეული ზეთი', 'სანელებლები', 'მარილი', 'ყველის ფხვნილი'],
    isHealthy: false,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Doritos.jpg/250px-Doritos.jpg',
  },
  {
    id: 'snickers',
    name: 'Snickers',
    category: 'snacks',
    servingSize: '50 გ',
    servingG: 50,
    calories: 245,
    sugar: 27,
    protein: 4.4,
    fat: 12,
    carbs: 32,
    ingredients: ['შაქარი', 'თხილი', 'რძის შოკოლადი', 'გლუკოზის სიროფი', 'რძის ფხვნილი', 'კაკაოს კარაქი'],
    isHealthy: false,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Snickers.jpg/250px-Snickers.jpg',
  },
  {
    id: 'kitkat',
    name: 'KitKat',
    category: 'snacks',
    servingSize: '41.5 გ',
    servingG: 41.5,
    calories: 213,
    sugar: 22,
    protein: 3,
    fat: 11,
    carbs: 26,
    ingredients: ['შაქარი', 'ფქვილი', 'კაკაოს კარაქი', 'რძის ფხვნილი', 'მცენარეული ცხიმი'],
    isHealthy: false,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Kit-Kat-Type-Variations.jpg/250px-Kit-Kat-Type-Variations.jpg',
  },
  {
    id: 'churchkhela',
    name: 'ჩურჩხელა (ნიგვზით)',
    category: 'snacks',
    servingSize: '100 გ',
    servingG: 100,
    calories: 410,
    sugar: 35,
    protein: 8,
    fat: 15,
    carbs: 62,
    ingredients: ['ყურძნის წვენი', 'ფქვილი', 'ნიგოზი'],
    isHealthy: false,
    healthNote: 'ქართული ტრადიციული საკვები. შეიცავს ბუნებრივ შაქარს და ნიგოზის სასარგებლო ცხიმებს, მაგრამ კალორიულობა მაღალია.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Churchxela.jpg/250px-Churchxela.jpg',
  },
  {
    id: 'tklapi',
    name: 'ტყლაპი',
    category: 'snacks',
    servingSize: '50 გ',
    servingG: 50,
    calories: 135,
    sugar: 28,
    protein: 0.5,
    fat: 0.2,
    carbs: 34,
    ingredients: ['ქლიავის ან ყურძნის პიურე'],
    isHealthy: false,
    healthNote: 'ბუნებრივი ხილის ფურცელი. შეიცავს მხოლოდ ბუნებრივ შაქარს, მაგრამ კონცენტრირებული სახით.',
    image: '/products/tklapi.svg',
  },
  {
    id: 'pringles',
    name: 'Pringles',
    category: 'snacks',
    servingSize: '100 გ',
    servingG: 100,
    calories: 520,
    sugar: 2.5,
    protein: 4,
    fat: 32,
    carbs: 55,
    ingredients: ['კარტოფილის ფხვნილი', 'მცენარეული ზეთი', 'სიმინდის სახამებელი', 'ფქვილი', 'მარილი'],
    isHealthy: false,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Pringles_Chip.jpg/250px-Pringles_Chip.jpg',
  },
  {
    id: 'dark-chocolate-85',
    name: 'შავი შოკოლადი 85%',
    category: 'snacks',
    servingSize: '25 გ',
    servingG: 25,
    calories: 150,
    sugar: 3.5,
    protein: 3,
    fat: 12,
    carbs: 6,
    ingredients: ['კაკაოს მასა', 'კაკაოს კარაქი', 'შაქარი'],
    isHealthy: true,
    healthNote: 'მცირე ულუფით მიღებისას შავი შოკოლადი ანტიოქსიდანტებითაა მდიდარი. 25 გ-ის ულუფა ნორმალურია.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Dark_chocolate_bar.jpg/250px-Dark_chocolate_bar.jpg',
  },
  {
    id: 'rice-cakes',
    name: 'ბრინჯის ხრაშუნა',
    category: 'snacks',
    servingSize: '30 გ',
    servingG: 30,
    calories: 115,
    sugar: 0.3,
    protein: 2.5,
    fat: 0.5,
    carbs: 25,
    ingredients: ['ბრინჯი', 'მარილი'],
    isHealthy: true,
    healthNote: 'დაბალკალორიული სნექი. შეიცავს მინიმალურ ცხიმსა და შაქარს.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Rice_cake.jpg/250px-Rice_cake.jpg',
  },

  // === თხილეული ===
  {
    id: 'walnut',
    name: 'ნიგოზი',
    category: 'nuts',
    servingSize: '30 გ',
    servingG: 30,
    calories: 196,
    sugar: 0.8,
    protein: 4.6,
    fat: 19.6,
    carbs: 4.1,
    ingredients: ['ნიგოზი'],
    isHealthy: true,
    healthNote: 'ომეგა-3 ცხიმოვანი მჟავებით მდიდარი. 30 გ (მუჭა) დღიური ნორმაა.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Walnut.JPG/250px-Walnut.JPG',
  },
  {
    id: 'almond',
    name: 'ნუში',
    category: 'nuts',
    servingSize: '30 გ',
    servingG: 30,
    calories: 173,
    sugar: 1.3,
    protein: 6.3,
    fat: 14.9,
    carbs: 6.1,
    ingredients: ['ნუში'],
    isHealthy: true,
    healthNote: 'ვიტამინ E-ით და მაგნიუმით მდიდარი. კარგი ცილის წყარო. 30 გ (23 ნუში) ოპტიმალურია.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Almonds.jpg/250px-Almonds.jpg',
  },
  {
    id: 'hazelnut',
    name: 'თხილი',
    category: 'nuts',
    servingSize: '30 გ',
    servingG: 30,
    calories: 188,
    sugar: 1.3,
    protein: 4.5,
    fat: 18.2,
    carbs: 5,
    ingredients: ['თხილი'],
    isHealthy: true,
    healthNote: 'კარგი ცხიმებით და მანგანუმით მდიდარი. სრულყოფილი სნექი ენერგიის მოსამატებლად.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Hazelnuts.jpg/250px-Hazelnuts.jpg',
  },
  {
    id: 'pistachio',
    name: 'ფისტა',
    category: 'nuts',
    servingSize: '30 გ',
    servingG: 30,
    calories: 159,
    sugar: 2.2,
    protein: 5.7,
    fat: 12.8,
    carbs: 8,
    ingredients: ['ფისტა'],
    isHealthy: true,
    healthNote: 'ყველაზე დაბალკალორიული თხილეულიდან. B6 ვიტამინით მდიდარი.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Pistachios_%28Roasted_and_Salted%29.jpg/250px-Pistachios_%28Roasted_and_Salted%29.jpg',
  },
  {
    id: 'cashew',
    name: 'კეშიუ',
    category: 'nuts',
    servingSize: '30 გ',
    servingG: 30,
    calories: 163,
    sugar: 1.7,
    protein: 5.2,
    fat: 13.1,
    carbs: 8.6,
    ingredients: ['კეშიუ'],
    isHealthy: true,
    healthNote: 'რკინით, თუთიითა და მაგნიუმით მდიდარი. კარგი არჩევანია ვეგეტარიანელებისთვის.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Cashew_Nut_or_Kasoy.jpg/250px-Cashew_Nut_or_Kasoy.jpg',
  },
  {
    id: 'peanut',
    name: 'არაქისი',
    category: 'nuts',
    servingSize: '30 გ',
    servingG: 30,
    calories: 170,
    sugar: 1.2,
    protein: 7.7,
    fat: 14.7,
    carbs: 4.6,
    ingredients: ['არაქისი'],
    isHealthy: true,
    healthNote: 'ცილით ყველაზე მდიდარი თხილეულიდან. ხელმისაწვდომი და საკვებად ღირებული.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Peanuts.jpg/250px-Peanuts.jpg',
  },
  {
    id: 'sunflower-seeds',
    name: 'მზესუმზირის თესლი',
    category: 'nuts',
    servingSize: '30 გ',
    servingG: 30,
    calories: 175,
    sugar: 0.8,
    protein: 6.2,
    fat: 15.3,
    carbs: 6,
    ingredients: ['მზესუმზირის თესლი'],
    isHealthy: true,
    healthNote: 'ვიტამინ E-ის ერთ-ერთი საუკეთესო წყარო. სელენიუმით მდიდარი.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Sunflower_seeds.jpg/250px-Sunflower_seeds.jpg',
  },
  {
    id: 'pumpkin-seeds',
    name: 'გოგრის თესლი',
    category: 'nuts',
    servingSize: '30 გ',
    servingG: 30,
    calories: 151,
    sugar: 0.4,
    protein: 8.5,
    fat: 12.8,
    carbs: 4,
    ingredients: ['გოგრის თესლი'],
    isHealthy: true,
    healthNote: 'მაგნიუმისა და თუთიის შესანიშნავი წყარო. ძალიან მაღალი ცილის შემცველობა.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Pumpkin_seeds.jpg/250px-Pumpkin_seeds.jpg',
  },
];
